# Generated by Django 4.2.1 on 2023-11-23 13:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('artist', '0014_alter_postupvote_voted_by_artists_and_more'),
        ('audience', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AudiencePost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('upvotes', models.IntegerField(default=0, null=True)),
                ('posted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='audience.audience')),
            ],
        ),
        migrations.CreateModel(
            name='PostUpvoteAudience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='audience.audiencepost')),
                ('voted_by_artists', models.ManyToManyField(blank=True, to='artist.artist')),
                ('voted_by_audiences', models.ManyToManyField(blank=True, to='audience.audience')),
            ],
        ),
    ]
