# Generated by Django 4.2.1 on 2023-11-17 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artist', '0002_artistpost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artistpost',
            name='upvotes',
            field=models.IntegerField(null=True),
        ),
    ]
