# Generated by Django 4.2.1 on 2023-11-17 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artist', '0003_alter_artistpost_upvotes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artistpost',
            name='upvotes',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
