# Generated by Django 4.2.1 on 2023-11-19 19:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('artist', '0004_alter_artistpost_upvotes'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostUpvotes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_upvotes', models.IntegerField(default=0)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='artist.artistpost')),
                ('voted_by', models.ManyToManyField(to='artist.artist')),
            ],
        ),
    ]
