# Generated by Django 4.2.1 on 2023-11-19 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artist', '0005_postupvotes'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PostUpvotes',
            new_name='PostUpvote',
        ),
    ]
