# Generated by Django 4.2.1 on 2023-11-19 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artist', '0010_alter_postupvote_total_upvotes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postupvote',
            name='total_upvotes',
        ),
    ]
