# Generated by Django 4.2.1 on 2023-11-19 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audience', '0001_initial'),
        ('artist', '0012_rename_voted_by_postupvote_voted_by_artists'),
    ]

    operations = [
        migrations.AddField(
            model_name='postupvote',
            name='voted_by_audiences',
            field=models.ManyToManyField(to='audience.audience'),
        ),
    ]
